* Cartpole Environment

This environment follows the same dynamics as the [[https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py][gym implementation]] built on the [[https://madrona-engine.github.io/][Madrona game engine]].

** Installation

If you have already followed the instructions from the [[file:../../README.md][main README]], Cartpole should already be installed. Otherwise, follow the following directions:

#+begin_src bash
  conda create -n madrona python=3.10
  conda activate madrona
  pip install torch numpy tensorboard

  git clone --recurse-submodules https://github.com/bsarkar321/madrona_rl_envs
  mkdir build && cd build
  cmake ..
  make -j
  cd ..

  pip install -e .
#+end_src

#+begin_quote
On some systems, you may need to specify the cuda toolkit directory for cmake as follows:

#+begin_src bash
  cmake -D CUDAToolkit_ROOT=/usr/local/cuda-12.0 ..
#+end_src
#+end_quote

** Testing

*** Correctness

For testing correctness, ensure that the madrona conda environment is active and you are in the scripts directory.

*For all of the following commands, the last line should be "Error rate: 0.0" but due to floating point arithmetic there may be occasional errors*

Verify that gym installation passes tests:
#+begin_src bash
  python cartpole_example.py --num-envs 32 --verbose --validation --asserts --use-baseline
#+end_src

Verify that CPU version passes tests:
#+begin_src bash
  python cartpole_example.py --num-envs 32 --verbose --validation --asserts --use-cpu
  python cartpole_example.py --num-envs 1000 --verbose --validation --asserts --use-cpu
#+end_src

Verify that debug GPU version passes tests (note: remove /tmp/bugcartcache if it exists):
#+begin_src bash
  MADRONA_MWGPU_KERNEL_CACHE=/tmp/bugcartcache python cartpole_example.py --num-envs 32 --verbose --validation --asserts --debug-compile
  MADRONA_MWGPU_KERNEL_CACHE=/tmp/bugcartcache python cartpole_example.py --num-envs 1000 --verbose --validation --asserts --debug-compile
#+end_src

Verify that optimized GPU version passes tests (note: remove /tmp/cartcache if it exists):
#+begin_src bash
  MADRONA_MWGPU_KERNEL_CACHE=/tmp/cartcache python cartpole_example.py --num-envs 32 --verbose --validation --asserts
  MADRONA_MWGPU_KERNEL_CACHE=/tmp/cartcache python cartpole_example.py --num-envs 1000 --verbose --validation --asserts
#+end_src

*** Performance

After validating correctness, we can determine the simulation throughput (in terms of steps * worlds / sec). Note that, in general, throughput increases as the number of environments increases.

To test the baseline (gym python implementation), run the following command. Note that Python's multiprocessing library may limit the number of environments you can create; for my system, the optimal throughput was at 32 environments.
#+begin_src bash
  python cartpole_example.py --num-envs 32 --use-baseline
#+end_src

To test the madrona versions for cpu and gpu, run the following commands:
#+begin_src bash
  python cartpole_example.py --num-envs 32 --use-cpu
  MADRONA_MWGPU_KERNEL_CACHE=/tmp/cartcache python cartpole_example.py --num-envs 32
#+end_src

When testing using 8 cores of an AMD EPYC 7402 Processor, an A40 GPU, and 64 GB RAM, I get the following performance numbers:
| num-envs | baseline | madrona cpu | madrona gpu |
|----------+----------+-------------+-------------|
|       32 | 37000    |      197000 |      636000 |
|      100 | 28000    |      572000 |     1880000 |
|     1000 | -        |     2580000 |    17500000 |
|    10000 | -        |     4130000 |   175000000 |
|   100000 | -        |     1760000 |   891000000 |
|  1000000 | -        |     1770000 |  1370000000 |

** Training

You can train agents using cleanrl's PPO implementation modified to use these new environments. In particular, you can use cartpole_train_torch.py for training in pure pytorch (recommended for madrona) or cartpole_train_numpy.py if you want to compare against the baseline versions. Note that the hyperparameters used below are just given as examples; they will not train a policy to convergence.

Pure pytorch:
#+begin_src bash
  MADRONA_MWGPU_KERNEL_CACHE=/tmp/cartcache python cartpole_train_torch.py --num-envs 32 --madrona True --num-steps 200 --total-timesteps 160000
#+end_src

Baseline (with numpy):
#+begin_src bash
  python cartpole_train_numpy.py --num-envs 32 --madrona False --num-steps 200 --total-timesteps 160000
#+end_src
